In [1128]:
import pandas as pd

In [191]:
file = "D:\\My Personal Documents\\Learnings\\Data Science\\Data Sets\\Twiter Sentiment Analysis\\train_E6oV3lV.csv"
test = 'D:\\My Personal Documents\\Learnings\\Data Science\\Data Sets\\Twiter Sentiment Analysis\\test_tweets_anuFYb8.csv'
tweets = pd.read_csv(file)
test_tweets=pd.read_csv(test)

In [192]:
tweets.head(20) 

id  label                                              tweet
0    1      0   @user when a father is dysfunctional and is s...
1    2      0  @user @user thanks for #lyft credit i can't us...
2    3      0                                bihday your majesty
3    4      0  #model   i love u take with u all the time in ...
4    5      0             factsguide: society now    #motivation
5    6      0  [2/2] huge fan fare and big talking before the...
6    7      0   @user camping tomorrow @user @user @user @use...
7    8      0  the next school year is the year for exams.ðŸ˜...
8    9      0  we won!!! love the land!!! #allin #cavs #champ...
9   10      0   @user @user welcome here !  i'm   it's so #gr...
10  11      0   ↝ #ireland consumer price index (mom) climb...
11  12      0  we are so selfish. #orlando #standwithorlando ...
12  13      0  i get to see my daddy today!!   #80days #getti...
13  14      1  @user #cnn calls #michigan middle school 'buil...
14  15      1  no comment!  in #australia   #opkillingbay #se...
15  16      0  ouch...junior is angry😐#got7 #junior #yugyo...
16  17      0  i am thankful for having a paner. #thankful #p...
17  18      1                             retweet if you agree! 
18  19      0  its #friday! 😀 smiles all around via ig use...
19  20      0  as we all know, essential oils are not made of...

In [193]:
tweet_label = tweets['label']

In [194]:
tweet_text=tweets['tweet']

In [195]:
tweets=tweets.append(test_tweets)


C:\Amrendra\Anaconda\lib\site-packages\pandas\core\frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)


In [196]:
tweets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49159 entries, 0 to 17196
Data columns (total 3 columns):
id       49159 non-null int64
label    31962 non-null float64
tweet    49159 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.5+ MB


In [197]:
cleaned_tweet = tweets.tweet.str.replace("[^a-zA-Z]", " ")
#cleaned_tweet = tweets.tweet.str.replace("@user", "")

In [198]:
cleaned_tweet.head(20)

0       user when a father is dysfunctional and is s...
1      user  user thanks for  lyft credit i can t us...
2                                   bihday your majesty
3      model   i love u take with u all the time in ...
4                factsguide  society now     motivation
5           huge fan fare and big talking before the...
6       user camping tomorrow  user  user  user  use...
7     the next school year is the year for exams    ...
8     we won    love the land     allin  cavs  champ...
9       user  user welcome here    i m   it s so  gr...
10          ireland consumer price index  mom  climb...
11    we are so selfish   orlando  standwithorlando ...
12    i get to see my daddy today        days  getti...
13     user  cnn calls  michigan middle school  buil...
14    no comment   in  australia    opkillingbay  se...
15    ouch   junior is angry     got   junior  yugyo...
16    i am thankful for having a paner   thankful  p...
17                               retweet if you 

In [199]:
cleaned_tweet = cleaned_tweet.apply(lambda x: ' '.join([text for text in x.split() if len(text)>2 and text!='user']))

In [200]:
from nltk.stem.porter import PorterStemmer
stem = PorterStemmer()
#stem.stem(cleaned_tweet)
cleaned_tweet = cleaned_tweet.apply(lambda x: ' '.join([stem.stem(text) for text in x.split() if len(text)>2]))

In [201]:
c_tweet=[]
for t in cleaned_tweet:
    t1=re.sub("\S*\d\S*", "", t).strip()
    c_tweet.append(t1)

cleaned_tweet=c_tweet

In [202]:
cleaned_tweet

['when father dysfunct and selfish drag hi kid into hi dysfunct run',
 'thank for lyft credit can use caus they don offer wheelchair van pdx disapoint getthank',
 'bihday your majesti',
 'model love take with all the time',
 'factsguid societi now motiv',
 'huge fan fare and big talk befor they leav chao and pay disput when they get there allshowandnogo',
 'camp tomorrow danni',
 'the next school year the year for exam can think about that school exam hate imagin actorslif revolutionschool girl',
 'won love the land allin cav champion cleveland clevelandcavali',
 'welcom here',
 'ireland consum price index mom climb from previou may blog silver gold forex',
 'are selfish orlando standwithorlando pulseshoot orlandoshoot biggerproblem selfish heabreak valu love',
 'get see daddi today day gettingf',
 'cnn call michigan middl school build the wall chant tcot',
 'comment australia opkillingbay seashepherd helpcovedolphin thecov helpcovedolphin',
 'ouch junior angri got junior yugyoem omg',

In [203]:
 from sklearn.feature_extraction.text import CountVectorizer

In [204]:
bow_vectorizer= CountVectorizer(max_df=0.90, min_df=2, stop_words='english')

In [205]:
bow = bow_vectorizer.fit_transform(list(cleaned_tweet))

In [222]:
bow.shape

(49159, 15145)

In [207]:
bow_train=bow[:31962]
bow_test=bow[31962:]

In [208]:
from sklearn.model_selection import train_test_split

In [209]:
x_train_bow,x_test_bow, y_train,y_test = train_test_split(bow_train,tweet_label, test_size=0.2, random_state=1)

In [210]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB

In [211]:
clf_tf = MultinomialNB()
clf_tf.fit(x_train_bow,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [212]:
test_pred=clf_tf.predict(x_test_bow)

In [213]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [214]:
metrics.accuracy_score(test_pred,y_test)

0.9486938839355545

In [215]:
confusion_matrix(test_pred,y_test)

array([[5778,  146],
       [ 182,  287]], dtype=int64)

In [216]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
skf = StratifiedKFold(n_splits=10)
params = {'alpha': [0.001,0.01,0.1,0.9]}
nb = MultinomialNB()
gs = GridSearchCV(nb, cv=skf, param_grid=params, return_train_score=True)

In [217]:
gs.fit(x_train_bow,y_train)
nb.get_params().keys()

dict_keys(['alpha', 'class_prior', 'fit_prior'])

In [218]:
gs.best_estimator_

MultinomialNB(alpha=0.001, class_prior=None, fit_prior=True)

In [219]:
clf_tf = MultinomialNB(alpha=0.01)
clf_tf.fit(x_train_bow,y_train)

MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True)

In [220]:
test_pred=clf_tf.predict(bow_test)
test_pred=pd.DataFrame(test_pred)

In [221]:
import pandas as pd
test_pred.to_csv('submit.csv',index=False)
test_pred.shape

(17197, 1)

In [1159]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [429]:
tfidf= TfidfVectorizer()

In [430]:
tfidf= tfidf.fit_transform(list(cleaned_tweet))

In [431]:
tfidf_train=tfidf[:31962]
tfidf_test=tfidf[31962:]

In [301]:
tfidf_test.getrow

<bound method csr_matrix.getrow of <17197x48678 sparse matrix of type '<class 'numpy.float64'>'
	with 166401 stored elements in Compressed Sparse Row format>>

In [264]:
x_tf=pd.DataFrame(tfidf_train.toarray(),columns=tfidf_train.get_feature_names())

MemoryError: 

In [432]:
x_train_tf,x_test_tf, y_train_tf,y_test_tf = train_test_split(tfidf_train,tweet_label, test_size=0.2, random_state=3)

In [433]:
tf_idf = MultinomialNB()
tf_idf.fit(x_train_tf,y_train_tf)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [434]:
x_test_tf.shape

(6393, 38973)

In [435]:
tf_pred=tf_idf.predict(x_test_tf)
tf_pred.shape

(6393,)

In [436]:
metrics.accuracy_score(y_test_tf,tf_pred)

0.9372751446895041

In [437]:
test_pred_tf=tf_idf.predict(tfidf_test)

In [438]:
test_pred_tf=pd.DataFrame(test_pred_tf)
test_pred_tf.to_csv('submit_tf.csv',index=False)

In [316]:
test_pred_tf.shape

(17197, 1)

In [313]:
tfidf_test.shape

(17197, 48678)

MemoryError: 

In [251]:
print(x_test_tf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [268]:
 from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.shape)


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
(4, 9)


In [271]:
X.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [286]:
corpus

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.',
 'Is this the first document?']